import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row">
          <aside className="h-screen border-r bg-gray-50 w-72">
            <Navbar />
          </aside>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
